steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/patient-remote-monitor/github.com/abhinavkrin/patient-remote-monitor-server:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/patient-remote-monitor/github.com/abhinavkrin/patient-remote-monitor-server:$COMMIT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'patient-monitor-backend',
        '--image=gcr.io/patient-remote-monitor/github.com/abhinavkrin/patient-remote-monitor-server:$COMMIT_SHA',
        '--region=us-central1',
      ]
options:
  machineType: 'E2_HIGHCPU_8'